/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(decode_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7c7daf24d324314a6d1d90dc26428f8e) */
/***********************************************************************************/


#include <gnuradio/block.h>
#include <gnuradio/basic_block.h>
#include <gnuradio/sync_block.h>
#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <iostream>


namespace py = pybind11;

#include "decode_ff_python.h"
#include <gnuradio/ale/decode_ff.h>

// pydoc.h is automatically generated in the build directory
#include <decode_ff_pydoc.h>

void bind_decode_ff(py::module &m) {
    py::class_<gr::ale::decode_ff, gr::block, std::shared_ptr<gr::ale::decode_ff>>(m, "decode_ff")
        .def_static("make", &gr::ale::decode_ff::make,
            py::arg("freq"), py::arg("wdir"), py::arg("wsec"));
}

