/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(decode_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7c7daf24d324314a6d1d90dc26428f8e) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include "decode_ff_python.h"

// pydoc.h is automatically generated in the build directory
#include <decode_ff_pydoc.h>

void bind_decode_ff(py::module &m) {

  using decode_ff = gr::ale::decode_ff;

  py::class_<decode_ff, gr::block, gr::basic_block, std::shared_ptr<decode_ff>>(
      m, "decode_ff", D(decode_ff))

      .def(py::init(&decode_ff::make), py::arg("freq"), py::arg("*wdir"),
           py::arg("wsec"), D(decode_ff, make))

      ;
}
